# SPDX-FileCopyrightText: 2024 SAP edge team
# SPDX-FileContributor: Kirill Satarin (@kksat)
# SPDX-FileContributor: Manjun Jiao (@mjiao)
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = "./*"
SPDX-FileCopyrightText = "2024 SAP edge team"
SPDX-License-Identifier = "Apache-2.0"
